hash-format = "sha256"

[[files]]
file = "config/AdvancedBackups.properties"
hash = "28b1af7e1ccd9695166ec1df33e0d08c1ec078e6e186e0b2e8c0228fe9e10acf"

[[files]]
file = "config/bluemap/core.conf"
hash = "b942611c074c37431c5c24d6d63faaf731e5e3b0a4f210370f3237617031b89e"

[[files]]
file = "config/bluemap/webserver.conf"
hash = "8d873e188b88f5eb15af95caccb4eb2d9732ff1b4920c0ebe8facd97e956021e"

[[files]]
file = "config/fabric-seasons.json"
hash = "892f326e5494be3b5fded6a644f0243d5a48583651d2b8ae675e671f792b7bd8"

[[files]]
file = "config/iris.properties"
hash = "99ac8a2dfd17f7b4ed038c02255a279296ecad90e48a5b7196ac4f73260d57ee"

[[files]]
file = "config/worldedit/schematics/butler.schem"
hash = "b3304afb33cd9ebfced2c06b990dd3e20675a64a35589c156b0b06630129d9f4"

[[files]]
file = "config/worldedit/schematics/mcc.schem"
hash = "84a3c8848190eb4832f8e47798ba686a35d83e682f01f3d7ba8b228acce9f0e2"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "95495226d48919c172eee4119a280275cdf0d63837a282878bce6ae4c66b14d5"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "408e7f0df62763aa355abbca8293e5e4ee8fe3ac687657768fd51fd96f164d78"

[[files]]
file = "mcc_com.png"
hash = "5f863af43a9d70fb16869d49f51f1df91677140da84b09f4bdc17815e3c9c34f"

[[files]]
file = "mcc_square.png"
hash = "58f04aaad383a08b9ddbe72280b1db0acf995ec1c3510581db49b7bb87c0778d"

[[files]]
file = "minescript/config.txt"
hash = "4dcf7855abb3439f00d76ba676653eeb01ffc529babc0a2bdd1bb37d144a6833"

[[files]]
file = "modpack-info.json"
hash = "1c7980231bba2a5c381eab7fc27c480a727929a4b43595a3b792aa7ec846fc70"

[[files]]
file = "mods/adorn.pw.toml"
hash = "3f61061d9264fca6e9bac1d2528797d6ab8ab9de508b057b020f788cbe7a70c8"
metafile = true

[[files]]
file = "mods/advanced-backups.pw.toml"
hash = "eec26a02ae733113e66a324e471eb01c24fb8739804592cd5c65c8d6a9ee9a72"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "6fcdc289a55f3d7c83a23be77f0eb62ae9d69c86fa5eeb24b41b2875de9bc85f"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "9ce55dc09b4b2a28b39ae47d146cfe5399dfc74666d9ae53811bdef4058b3491"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "39792a11da59cebc770f3918dd0ad53637bcbd206dc19bfa6709392bfd2d1830"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "6710eac4f0afbf236eedcbca6304179defc933faf68608c83b3e02b215e507e2"
metafile = true

[[files]]
file = "mods/artsandcrafts.pw.toml"
hash = "56d40764d6dca7ecda2a80f10fc0caeac8f90a120830f4827b2297976caaef8e"
metafile = true

[[files]]
file = "mods/athena.pw.toml"
hash = "fff0b46fc8b9e9c44f4b6af6ce8c90d12e79b955506f6884986647011d92abc6"
metafile = true

[[files]]
file = "mods/autowhitelist.pw.toml"
hash = "3a631fd09fe5973933295b7ad068366d6015c10c97a4d098c4993b3e4e77ce2a"
metafile = true

[[files]]
file = "mods/axiomtool.pw.toml"
hash = "e095b86ace2ba079e80dbc188be0f3f7f750d49f0113a3d6c77dd3e3f931d54f"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "29134bdd10f9cc82fbdf0a35fe9ad7aec91222af18e230b3389e016589860974"
metafile = true

[[files]]
file = "mods/balm-fabric.pw.toml"
hash = "c4fcbd3048f4904d0326fcfe99decb08f58b0da27c2858db09f02a21a3f12b64"
metafile = true

[[files]]
file = "mods/better-sleep.pw.toml"
hash = "d583c95064e14827a70131c4d4515c2ca61fed7692cee825692b895516463708"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "6f530660a6b3bc694db34a852c17f4c67f64264fb22e33b0b45c46facbb7fbb2"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "9321ca8fcfede6fc41a135553a4ed456171242345c400aa88c951aad38bf7d46"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a26fa538ff65bfa90d5abc69b712f6e8f04e18759315ea1ae7402e271f1c4797"
metafile = true

[[files]]
file = "mods/chunky-pregenerator.pw.toml"
hash = "8c0563c333d9841731f5a41cc0314d921fa98f579c9b7909749d1379df61f988"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "9e21cc4fae5ed88e306b4601c5e1533f883aa8b60c6e36dedeec82718be87059"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "7ec9fd19e018b8bb8f6e6aae2ee691c4c843d363a650d52d40fa300b329d6ac9"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "c95f96c1422ed285de47a75dd9c163538fe89259d9525d15d2c07039f0c1f5b1"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "68baa76bba0cca586ce73f60b6c525b1e1c53a4d086efe069c814b9c4a961d54"
metafile = true

[[files]]
file = "mods/creativecore.pw.toml"
hash = "7112f698dda447ec4f1c6474683308487d51e93ec8dbe26c7f81d0fdd4c9fdb0"
metafile = true

[[files]]
file = "mods/distant-horizons.pw.toml"
hash = "3a0da1a01f5281b39b00612f283b405e2d6c64d058cdf0571982a60480afe048"
metafile = true

[[files]]
file = "mods/effortless.pw.toml"
hash = "fb15c2081315f5d57a085056246f0f2c221e318bb81564ca631220fea650bb35"
metafile = true

[[files]]
file = "mods/excessive-building.pw.toml"
hash = "6d6eb5f612975125b74850e8bafda5d8d521c543e9f749d9a015d830ba38c123"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "0e28ba15ba1769864a4af0b2f7ffaa3c90017b49633bef2a843b14a46e9a791d"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "1aa94f817646eea69478dc3dce662c3f4b674359d7ce34cf58fd38dcbc56e458"
metafile = true

[[files]]
file = "mods/fabric-seasons-extras.pw.toml"
hash = "7833078d6daef78131f8cc43425ef5292413e966154ac3ce305e17196bd530e2"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "d40faa8d75ec7b4741146b033dca1d47368868985da3dcc6dc32fd9def5841d9"
metafile = true

[[files]]
file = "mods/fabricord.pw.toml"
hash = "5749724ac7f1331ec4bd6469e93b650501e3d4e455c750c7b9068f99c9574c9d"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "c166eaa8e7a8083b93ee31438798ec1bfbc2f9758f13279b5db43f9702517b00"
metafile = true

[[files]]
file = "mods/ferritecore-fabric.pw.toml"
hash = "1bcebf42f650151bf068b968e2b27b05c4b278bb9a31f2c0b64c4a462d3ff787"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "e890d5f92003bac971ac9f1fd1e6b3bd01cde0f8e44bbc939dd3c96dc6e83cfc"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "d0e586bf4b4f9f003b1de1a3e18f67540233a0295b487009047056198f694f0f"
metafile = true

[[files]]
file = "mods/gamemode-unrestrictor.pw.toml"
hash = "ba71e8e6fb12af4d7c9348f572fea999ea6b614356b12b708ce99a1157e82e00"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "00eaafc399810122b7522b172e12aec41f8d8b787192a78362f77e1274c21451"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c86e0fe57fbe042c8444a9c63933e89b5fdd50f325bb8a9796d0e7cca8735c89"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "9c5c952960bc5bac9df87872a305acd62791aaa9183bae8ad2d69524d76da350"
metafile = true

[[files]]
file = "mods/jinxedlib.pw.toml"
hash = "c386694b015da78a44653e4fddf66718f7492a868664f306007e75b2a8aceec9"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "252b6581ba3fa2cce52a4bdf114020a2e7e069a42b35b6187ac3e21141b3a00a"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "e969c54f8b34ce0c793672e47ded8de32b40a71f4e9a73ca0947c5ce6390d63f"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "9b854e39b03b0b813b1ebb8834297ef39ae79195799e00a3b96c50cfa5ea9c38"
metafile = true

[[files]]
file = "mods/konkrete-fabric.pw.toml"
hash = "c51a2b21847608f50773378886e3503e4ae22b55b8a69cc9bd9016f089f84995"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "f7c9c1bee75968286a4fb6a765f7cd0505fac90cac30a896f76215c1e6d4d8bd"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farm-charm-compat.pw.toml"
hash = "64c46fec3e0545fffddca8ba907ad0f8d812fd0ddcb5a6e6f1aa78b1a542291b"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "42c866cdc38fc88ed6f4e79fc79a801c3c70d52a4a9948c37da04b77b210151d"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "eb1cc493118616c53564e5072d21e25dadc98b1765e5507a1b181c2632145f35"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "804bd885dd40336596175503d631ab7f529ad12e152872462b1c25f15b2f89bd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0f8827c966b0d439692f3b8d578a47c203cd0aec0043ea4fd3fc00025a13ab79"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "89b3efcfbb620fcab438c727a9e7e3a3d8fbf889ec56c579446f9dd888a2db26"
metafile = true

[[files]]
file = "mods/little-joys.pw.toml"
hash = "2e774e5815de5f6aba79e5f7cbb686580c71bb451f4b7b339be3b8ea20626c0f"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "ef3f71f992c06db063797fef0fcc16143cb48e90d069918f0767e3e0ecf560df"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "88e28dcf21277be5381110796df15d6c897e402fee1ebdccfa3fa57a9e957dce"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "9263b8e4a719799ddad59085304184c2889d6cee52837ddd21e06f24167ab1d6"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "eaf43a9f40e52d6ba5c7d6cc96ebf9ffa30be227b0ad8b8bbc5dc44d9f82e5e9"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "bc28fb6c8cd9cf427b7cad7f8f297825d56a027499386656d941a2020114ce74"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "bc3caff634957b995501db21881a51e539e50f9b28321ca8f7065c050dc0bacf"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "e9e92f0ef76acd14e23740fa8c15a9d6039e34f17f1a50fa55598b9317db52fa"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "40e83bda8afbed690756ed0ee7726fbbbb585d2d6589e867bcb1f64a38335754"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/minescript.pw.toml"
hash = "5647dccd17b9e6bc087d8a228bfc91ba7bb13acdc99d68820e281b9271f66133"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "756e9021d46a85cc4a8f89e9f71c0ac6031e8e40b41004fd2915bf2cbe64cd99"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "3cd8155341a4233955ff9892a3b7b5da6dc6d8d892863b2f544328f2731f7f03"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "93ef4a37c097bbdebaad5fd38db9cd6f823e86e9a4f338d1d6901413a7a3e647"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "e3c482b20c0bb250716495a2c05efae13b520849de1cfb27ea2ad704fb325873"
metafile = true

[[files]]
file = "mods/reframed.pw.toml"
hash = "b6021cd52db0eee9a48d1aa31552d1158bf8b454b424ea0ddda9011e324efa0b"
metafile = true

[[files]]
file = "mods/reintegrated-arts-and-crafts.pw.toml"
hash = "b8a110174a694146b0d6fa1673c4dfde9ed7a3143dd807fdbb5b982718f908ca"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "8deb4040131569c97902b40e0d81ef80330c6bb477c2ebcf5a5d987e1348eb96"
metafile = true

[[files]]
file = "mods/roughly-enough-items.pw.toml"
hash = "a01882a8a94bcf77e68f3d03d8a1d3098de9b63ee455d7ee0ee300bc8974b2c7"
metafile = true

[[files]]
file = "mods/sawmill.pw.toml"
hash = "61a1c2259695285d86e39ac1e1ef4e656e83c49fa8541b5c8a89e0682bde5b1d"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "795a73207734f08e5cece4da342c509d2210787ea8f0df9ea7ee440719a53cf3"
metafile = true

[[files]]
file = "mods/selene.pw.toml"
hash = "d4a9adedb76dd0331ace24c1b3ad5883ffca3f644906911f2271fdcf97cf259f"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "e481880fef8eb75f680175d3485055d339d806516254081e66dc51c9a78c1a4d"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "1a887f5c1e880d63578356e7fc1eb3698545238ad8ff422268dbb23eab7f9ded"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "f73a48751e13380b87296e5b9627c9f6669efda386bd646fd5c499b344570f46"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f5031d53eb32a7b25e0c2347f599805679a49073b86ed4450ca60ec9b72086d1"
metafile = true

[[files]]
file = "mods/storage-drawers.pw.toml"
hash = "0e3ae775f6caaa4b69262401f8c17735a36f21e942633c6e257dfa20a169e561"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "124f4508c67f28ea329df65f34de0f7200f8acf6d101daba3f674232c2b2d013"
metafile = true

[[files]]
file = "mods/underlay.pw.toml"
hash = "c9b845fadb2160ec733870d1e8ef6a3d5c6c201ec2dbc517233df0bf6861f5b7"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "8876ed7fdc1ad94eb650e0ce6b1dc45b35c3b7b607d0b51c4d58b839335894c0"
metafile = true

[[files]]
file = "mods/waterframes.pw.toml"
hash = "4fac4b6727b7810ee41bf3288ede74f9733ab4130d511596d71fcbcc349acba5"
metafile = true

[[files]]
file = "mods/watermedia-yt-plugin.pw.toml"
hash = "e0b5d86b63b2aa52bf50d3b58280fed584f8cfef65edc32e7a8b317690e877bc"
metafile = true

[[files]]
file = "mods/watermedia.pw.toml"
hash = "9c14d2011a343872dfa72aee64ef7beb2f9f9e47867807b4b03726cfa8e429b7"
metafile = true

[[files]]
file = "mods/watervision.pw.toml"
hash = "8c3bcaf2adc74254e986a5c9a63a9519e21630e2aaacaf600a7ad34e9cae8bea"
metafile = true

[[files]]
file = "mods/windchime-unofficial-continued.pw.toml"
hash = "c9cedbfb4c75d06046a3281fefaf35096f35372727e567244fe7df9a4a6b1e88"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "0ad78994efa02d9de2cb4ee015b2db4f927f92217848d882c14c24f4c1224b4a"
metafile = true

[[files]]
file = "options.txt"
hash = "abedd35219c3943cba8350ddc9eee1d1cda55e9ff5daff1b82c331a412b83cb2"

[[files]]
file = "server.properties"
hash = "00afe7fece2b78adee18cf2ea96e1ffdd3fb5ccfe1838be6dd671f7b03c5d0b4"

[[files]]
file = "shaderpacks/BSL_v10.0.zip"
hash = "b6e79a4f5746bd0b2bd8d54bb4c430539e7e747e8679ac985bc07368422e4e09"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
hash = "33153747d25fbee470acb42ccf4f26b03cc551bb900d4c6d3389b5500dd84839"
