hash-format = "sha256"

[[files]]
file = ".claude/settings.local.json"
hash = "006b41394f6351fbbed2cc67b30675f7987525886c6df107c0de34f3589ffa24"

[[files]]
file = "CHANGELOG.md"
hash = "c829b2917f8a1ecb1b4fc1c32f176f0bc0791ccf42dc10a3d23621ba815b8e86"

[[files]]
file = "CLAUDE.md"
hash = "d3f2ddad5271580f19b31bed47df929e6c790b0e0b67294994317d6d884409b2"

[[files]]
file = "README.md"
hash = "7c929c70c4b4211404e4a50e0938609b4bbb9b485c2f152ced74b5005575daa7"

[[files]]
file = "config/discord-mc-chat/discord-mc-chat.json"
hash = "6e6e7dd8749a8448f85996a924f57dfbdfe68f2e485480846ea7f481dfe4ea4d"

[[files]]
file = "config/iris.properties"
hash = "99ac8a2dfd17f7b4ed038c02255a279296ecad90e48a5b7196ac4f73260d57ee"

[[files]]
file = "docs/minecraft-college-setup-guide.md"
hash = "5d717577101ef8c5eced132a2ddf43338f78e0b0906cc01aac9a2828a54a08de"

[[files]]
file = "docs/server-plan.md"
hash = "bf520f7154bfb854775ed476f781ad462cab86ca68b67c56f4a8936baf82b557"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "95495226d48919c172eee4119a280275cdf0d63837a282878bce6ae4c66b14d5"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "408e7f0df62763aa355abbca8293e5e4ee8fe3ac687657768fd51fd96f164d78"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "5601649308a7d9f1658a942bbd48d3bd899a81fabd4ea1296952b48474d1ee1d"
metafile = true

[[files]]
file = "mods/better-sleep.pw.toml"
hash = "9c25456ace927353d49cdbc7210532a4cfd0a7732e2932732aa05e2a1d230a62"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "a4d21da45c40e8f1e3b76c9855ea3f1c15736cf2b12475e9de3efd05f8f48a8d"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "7fe287ca1bed0ad67f37e62a5816da7b7ae59486102c5e4b7532f0a999444527"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "eecdc8127f69c74ff55fd183d1f1d7d5ef3e714d73845a239fe9e086147a67b1"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "8827202405d0d549145059b55449836dad4d71aff21030d7390f2769daf0222c"
metafile = true

[[files]]
file = "mods/discord-mc-chat.pw.toml"
hash = "ba8b5da91075ac957c34a56cf6a3ab34616b6d6c998f59130cc73476012066d4"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "5a7c1b20dfbc7f9d4816afe5f0a842d8cb718f6c08e7f78aef47bababe8c078a"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "446f8047ee9168b65fe9d4600f82cb915c7aa0d0f049a344177ba340a5b93a8a"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "debc633d962665af2873b7e4c74a5bd8da18d6a883971e73b9039f9612f457b7"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "9fb4d588bd578e2f16a9605ff6303872130b36ccb0fdfff98bd7274da94f91b9"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "3a80b219be76a6802ac247de440615ec6f79e1093c56e98ea1e365bc292530d2"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "2600fb5f2efa6dffd1bcc04eea4c2646c101da4320da0c88d5616d5c2f41a439"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "80858e1b1477432110b72aab33348635139d6e8fe7bc05db3ba00651de635720"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "7375f12e54998e218a602ba71a0554dc1bcbd9cc56e152eed4174e86ddecb33c"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "c4e45594c8d1ab3dacc3b49142f16fb253178dd31d97cc917bf4a4d54f21e081"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "f5f134844b199b78f07b6f58ded80ee7b6a786d509a95687a2abb48e8dffee6b"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "f48382dc8ad6b473ed5e6d050038513e56697143b1232c1ae8ff40861f06ba2f"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "2a351e405d3bbf633a34f4a08deb1f4aacbcff960f4e6e44fbb67fe0e07e3044"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "99deb2f3aa9cd5d7eff3dd58e8acbb32662cbd448a10fd588c166786200e3019"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "8675eb41c4bb4fb257451f86a79ae35aae0ce5d88a061e1adcaede311c22f4aa"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "8d4ecc66f120419b4bc09fdd14151d2a207ddec30b46ae2184300fec0031b092"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "70ec6df06813b68cf3082c5a52339d32397c200f6acc8c02170453200bd79165"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "6803e0debba4fb27c735ccb139d26ae4c7744b8a7d2ac500d4f56b1d411faeea"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "7fc969e77edc3b0b9946b42070fd858349a74555f0cf9648907241af8a3a2d25"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "62df1cb449d5c6f8c5d670f14819a106a451e88102b8b066efeb73951f058d30"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "d22546ad55b555931eb527f163b3564e00c12c7dc8101378b87447dfcc8e0652"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "d3f633dd12cd039a4e58dd398d1c80a324b0d78b9da5b3972b69640bfed211ed"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "8302da862578554b012b2cfe58a3c1e75b514d09f94d842e7303be41a2157aeb"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "82a7a2d7cf37f5ceab22bcdacfd3206ede5a69c30b4f567a3976293e2231d30d"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "1c0d731cceb2515e4ba22318ac3d6bbd8bb670047cb5596d988725bc6e97b12a"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "9bdd041fb29ab003ef5bb1f0ba53516847e32e3010a3fce247f743fc98e08a6b"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "c7472ae71ab0b72df30939071422b0df04428e1e187a080f1e5f1df0cb1f2465"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "695176ca996e639044d0d526cd6c56a95c9897e85e7a8119a2d14a712f755733"
metafile = true

[[files]]
file = "options.txt"
hash = "5f30cc88a38375250345b391ce650516f78b73d8b2c041da4fca72c09e0f679d"

[[files]]
file = "shaderpacks/BSL_v10.0.zip"
hash = "b6e79a4f5746bd0b2bd8d54bb4c430539e7e747e8679ac985bc07368422e4e09"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
hash = "33153747d25fbee470acb42ccf4f26b03cc551bb900d4c6d3389b5500dd84839"
