hash-format = "sha256"

[[files]]
file = "DistantHorizons.sqlite"
hash = "6cf6e4733d08ed6119716848ccd503e2d11441a6771847cc12eb9d04a4aea92b"

[[files]]
file = "config/AdvancedBackups.properties"
hash = "5f286c969eaf7c31c3958b6ff8417333421e98844621b39ec23dc9d04396c4f8"

[[files]]
file = "config/bluemap/core.conf"
hash = "b942611c074c37431c5c24d6d63faaf731e5e3b0a4f210370f3237617031b89e"

[[files]]
file = "config/bluemap/webserver.conf"
hash = "8d873e188b88f5eb15af95caccb4eb2d9732ff1b4920c0ebe8facd97e956021e"

[[files]]
file = "config/fabric-seasons.json"
hash = "892f326e5494be3b5fded6a644f0243d5a48583651d2b8ae675e671f792b7bd8"

[[files]]
file = "config/iris.properties"
hash = "99ac8a2dfd17f7b4ed038c02255a279296ecad90e48a5b7196ac4f73260d57ee"

[[files]]
file = "config/worldedit/schematics/butler.schem"
hash = "b3304afb33cd9ebfced2c06b990dd3e20675a64a35589c156b0b06630129d9f4"

[[files]]
file = "config/worldedit/schematics/mcc.schem"
hash = "84a3c8848190eb4832f8e47798ba686a35d83e682f01f3d7ba8b228acce9f0e2"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "95495226d48919c172eee4119a280275cdf0d63837a282878bce6ae4c66b14d5"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "408e7f0df62763aa355abbca8293e5e4ee8fe3ac687657768fd51fd96f164d78"

[[files]]
file = "modpack-info.json"
hash = "c7c96045fba79e85c9ba939d325faf3583c688fe56a26c1ac3664b1101474528"

[[files]]
file = "mods/adorn.pw.toml"
hash = "977a19edbdb8cb2cd58449a64e3bd4caca780bb2b670ef843886198ae5766b7f"
metafile = true

[[files]]
file = "mods/advanced-backups.pw.toml"
hash = "bea7f27b65c3c952c789b7e663d5842575193acb528b7b2eaec4a9461acb72f8"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e9dbd0306dd34da5fe43f5880de09950d312ba7ab60880c69b555b197e2a1007"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5b9618476350398ad0d25b5bf3a41521dd015baa22e4bfe8db685625a3a2c697"
metafile = true

[[files]]
file = "mods/armor-statues.pw.toml"
hash = "73b0a6af0d4be59882d8ae1b0edd62e65c35171277cc9b3082331ad4b6c76850"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "dbc1220d5b4e4a1615ccecfb7d482349020919700ad9bafb5f690c2d4adbb5b2"
metafile = true

[[files]]
file = "mods/badpackets.pw.toml"
hash = "6ff12e37227232226f2fe51c0e34386540d417d06c75cb951eac01f8947bea68"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "6e39e7712a94830fbc2bd0b6ec73e03f54de5edfcca85da6e89a0021e9a3bf1a"
metafile = true

[[files]]
file = "mods/better-sleep.pw.toml"
hash = "642e862f4be77db00a3afd2105efb10b81d874e0afc32c621cf1bb7f087fe410"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "84d5506d7a81b89cb1abf6e2dd4d2cb0f5eed5b4587c19c73ffc2e954989019d"
metafile = true

[[files]]
file = "mods/camerapture.pw.toml"
hash = "3cc79a406a67f07707ed8676b1b5786d2112547dca4df21757ea5e54c7cfe72d"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "f6b6c905a485c11b69b8b6dcac0d0b78f0043c0869ec1ae99bb74bb2c88c93ee"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "8792552849464a56b066435132a3563a81e1ed70afedcc8c9dd1da602cda1d5f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a112512699928e5504f2e826194c60881f949902fee6c6bef5f3539fcb90db75"
metafile = true

[[files]]
file = "mods/connectiblechains.pw.toml"
hash = "e28f40d34c30c32d4bd05cfb80215c907b59e43d7e593ead73b3a04bb959bd4a"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "a2316b374cef47920604f89b1ce784aa3e1e4c80088259e7704ce5fe47c14721"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "c798b7e3414891c8db42e93335d21a104d40a235e35a6a42b47e0a213c9a6be9"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "b9cb49dc2d791b759ac553cf28ca33a6440d219f48ebc0ba4eb100df37c73889"
metafile = true

[[files]]
file = "mods/effortless.pw.toml"
hash = "fb15c2081315f5d57a085056246f0f2c221e318bb81564ca631220fea650bb35"
metafile = true

[[files]]
file = "mods/excessive-building.pw.toml"
hash = "07a95b7ec52fdfec7b28c93bec7dc5f1df4eaed698ac5d5bb692eaad8a88b951"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "27c4150b810e326b1097a7768c593c93e89484fcee0b8c4a8f3d48a6896cf649"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabric-seasons-extras.pw.toml"
hash = "7833078d6daef78131f8cc43425ef5292413e966154ac3ce305e17196bd530e2"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "d40faa8d75ec7b4741146b033dca1d47368868985da3dcc6dc32fd9def5841d9"
metafile = true

[[files]]
file = "mods/fabricord.pw.toml"
hash = "5749724ac7f1331ec4bd6469e93b650501e3d4e455c750c7b9068f99c9574c9d"
metafile = true

[[files]]
file = "mods/fairy-lights-fabric.pw.toml"
hash = "8909d8ae6c75018bd0ee408eb0980b55a0995d2e42e5729e398e6ec99319edb7"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "310deca3cd563b915d447e707bd138c3ff3ae0fd40f648daabacc7350437cd32"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "0ac4faa43fa6348191b94dfc7c0ed8a1b09f6dc3b36837b029aa023853019503"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "945c52db21b5c778f7292bbb4979fb844b2255168b15bf1eee2285c7ce5b6217"
metafile = true

[[files]]
file = "mods/forge-config-api-port.pw.toml"
hash = "238b3ceb4214a682480ce00eefae5d34efa299ff6ff667e4b2f2ed503c6e76ee"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "830613b40e4ceb047d011b00190f57c350d30fbc1d244c56722f4617ae2a57de"
metafile = true

[[files]]
file = "mods/immersive-aircraft.pw.toml"
hash = "ab5b5ecade1d9cf981d11fee68d5f42e5d933a4e4d9b15b2657d8da2a4f8304a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c86e0fe57fbe042c8444a9c63933e89b5fdd50f325bb8a9796d0e7cca8735c89"
metafile = true

[[files]]
file = "mods/itemswapper.pw.toml"
hash = "ad866f3cb389c13ccf4022931956c97a0f82a0f6b7940f8842a83e3b47a0a653"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "67fe6ad4a8c1b5f64a8b2ecd0aac7bcd7103447494df8f08fd8a4124411229a5"
metafile = true

[[files]]
file = "mods/joy-of-painting.pw.toml"
hash = "250a60ad345454a739a4ed90779501c31c90f5be387c3e52816ced6713012e98"
metafile = true

[[files]]
file = "mods/just-zoom.pw.toml"
hash = "bc39b827e5b14bf4a7a797b5aa72b03a09a25b229ba33da1fc0bea447cefafa1"
metafile = true

[[files]]
file = "mods/konkrete.pw.toml"
hash = "34d75daff8b8260780d97bbc2dc545739399df1d5ac304eeb2f80e23354cf3af"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8ecd67f8269c6317a0dc59edebcb9d6b3730f3adf26532e3a6c664804983c4ec"
metafile = true

[[files]]
file = "mods/lets-do-bakery-farmcharm-compat.pw.toml"
hash = "8d79f55134e2eeb31242a21db1bb59b4b7b6da028bf3ef798af2e8ad684d44ea"
metafile = true

[[files]]
file = "mods/lets-do-farm-charm.pw.toml"
hash = "1eaf02cf7c937ca8d1cf8c559af2b57fe896e0dac324effd54b9cf402dbe28a4"
metafile = true

[[files]]
file = "mods/lets-do-vinery.pw.toml"
hash = "d92ff27b876a352db391134ef6ebab2738ff9068641f1dde588ec07890c9b2f1"
metafile = true

[[files]]
file = "mods/litematica.pw.toml"
hash = "804bd885dd40336596175503d631ab7f529ad12e152872462b1c25f15b2f89bd"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0f8827c966b0d439692f3b8d578a47c203cd0aec0043ea4fd3fc00025a13ab79"
metafile = true

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "93a9d609533082c74458d94232b4883d0b77d88176c98a3824e2a5acb1a92d85"
metafile = true

[[files]]
file = "mods/little-joys.pw.toml"
hash = "4ba391dbb479324546527815c0a59cb1dce8e8da3177f91c64b991e415e4ba97"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "80474d91d72222900c31b5829a18d735942a08a14ea6e8bf61609770003f06cc"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "77bf6a03e9d6f74b1ed5d03095caa843ad15eb9a6e2a59c1d051dfb606084070"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "66365a7cd0eab491a46ffe6eea730bdc18a847acbf7427389b11523513f4d8ed"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "7a7a3dfab20334737bf31b367e484038b1b283eb9911a2a3bc4727700d2ae4a4"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "8814c7931c35f9c2c253cb4c3b62c120d1e14f608d3011e91ba303afc0154a53"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "9eb1325dc680a7bdba0ff97a27e3b6894b2177911518c7cb86aad32eef48adb6"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "5b341b230a1c90db349b54b27a8056a4651961836acb915c5dc68e882ab358f6"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "0b1d715cd850c6ce4c1bd42fdb331f5f79ff2e0e7b5138812f2156cdb5f60694"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "d9221689ffa47dcd27e6c0590ba7b3227f83d48a6e9592cd09e1835f143d793a"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "941a5aac1b441e2b4bd0c8465ea7e9f5c6826b4f99aa8c4ba63b3b657b6e7530"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "73c8968e0a12b2303c59f0991290fd0d6d7ac0566299314200beed9777f0fdc8"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "f0440bc0276d813e5de5f87388c8853e13842358383084571093600abc7d5a2f"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "72888447d9d18619c6260001033c1a8c81d27687717e920dea86147792ff1f73"
metafile = true

[[files]]
file = "mods/puzzles-lib.pw.toml"
hash = "44a6662d6ac604b2173a8bc426a10c0d621c8ba99d37d1b72525c140c42cb358"
metafile = true

[[files]]
file = "mods/reframed.pw.toml"
hash = "b6021cd52db0eee9a48d1aa31552d1158bf8b454b424ea0ddda9011e324efa0b"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "7775fd30aa27e84dbc3acb28ce34e4f703d1cd503786da5cb84f2813a57acf15"
metafile = true

[[files]]
file = "mods/reintegrated-arts-and-crafts.pw.toml"
hash = "a53f75beeb9d58db3a34febc79ae5f9f1c6bc3d31eaf2c218985ca2e74850b62"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "cb361ef34fb46e3fe719a08b08ba4ea8e0fda33927b8b23f1999c8e451bb02dc"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "bd1cc305fbff4a3b13f4406f22cf6c33bb4cb17dab0327e962e521c19a53c9ec"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "051f526e3f8a093006e2f0ed10a784647fa8e8ed738e9ccaa81f401ce5441e77"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a57a0cf4e8bc2b3997d03a3d1748a756d429bcc2f89e6814555ea4be846c279d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a987bcd2646a2ab741e7f609b43cb2d9c9daba765323b5a77d506b0ac7f4207"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f93fc683b99d7405f4d54cdd799e7adbc99388a10c44e0271acb11276de4a934"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "7ce16912c8ffa23e398c93c8060634ed3ded1fa4fe40384216b53193a1fd8a08"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "27670ced0491777862fb15dbf598df3b0dfc86b73f19874419dff12dc29e3c15"
metafile = true

[[files]]
file = "mods/underlay.pw.toml"
hash = "5e4972504aea845c8a84cc1c81c27ea22b1a8ddfd7475289f964f0446f9d8a68"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "177cfd45dd255736ca80f81e7a38e907dcce205e6d4cd2f8aa98602d92a57a30"
metafile = true

[[files]]
file = "mods/universal-sawmill.pw.toml"
hash = "5b27aeb2db9d4a77b78ec6d0b86a4b5c71d14b844e281731cbf07c6133ca88ef"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f1670113ba6c7687790c33c13521505caf0fb59a50a253e9533e9f6ebe3cf8c9"
metafile = true

[[files]]
file = "mods/wthit.pw.toml"
hash = "c2fe7ad62a2b0f218f952fdb96c0edff69c29a6aa9080adc5e91d012a4cb57a6"
metafile = true

[[files]]
file = "options.txt"
hash = "abedd35219c3943cba8350ddc9eee1d1cda55e9ff5daff1b82c331a412b83cb2"

[[files]]
file = "server.properties"
hash = "00afe7fece2b78adee18cf2ea96e1ffdd3fb5ccfe1838be6dd671f7b03c5d0b4"

[[files]]
file = "shaderpacks/BSL_v10.0.zip"
hash = "b6e79a4f5746bd0b2bd8d54bb4c430539e7e747e8679ac985bc07368422e4e09"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
hash = "33153747d25fbee470acb42ccf4f26b03cc551bb900d4c6d3389b5500dd84839"
