hash-format = "sha256"

[[files]]
file = ".claude/settings.local.json"
hash = "b0cb646fb535ab68b2bf3d1f448faf949b2361aaf1de096db6d27a1d4d922134"

[[files]]
file = ".env"
hash = "762129717208c743373730c9be8d6d995ad2cfc18c393432fbbc529028337af7"

[[files]]
file = ".env.example"
hash = "70535e20ae4e0f3edff09d661bbe3b2d244290e4001af76c9547d409cc6270a6"

[[files]]
file = "CHANGELOG.md"
hash = "b7ece828691f294ddffb7ac0c5f49eb6657da3c43d61d16ef8bbfbab15a8bc2c"

[[files]]
file = "CLAUDE.md"
hash = "7547522bf6744726757c64789501e16b57e4944291899eee74dc749ed32bfe13"

[[files]]
file = "LICENSE"
hash = "98d2c3c16836fcd6dcc509e9686423ea948e9df9f12182114e7093a030262e37"

[[files]]
file = "README.md"
hash = "afb0c153691a1f6175bd3504903bd7063c9f41ca7e7e2207acffc56cef45828f"

[[files]]
file = "__pycache__/server-config.cpython-314.pyc"
hash = "201e94729d6d646f5170573c954f1fd6a16d3d9a3ca532e1c9d80967d22a82cc"

[[files]]
file = "bluemap-5.6.jar"
hash = "3cf6fe0779f660b0da62369aa2cbe0d67b671e2ec09bb0283d63abe041f989ce"

[[files]]
file = "bluemap.jar"
hash = "67e7bd3037507c04ecfab8543222ad87552a81db85940c3c9935b2c517422fc4"

[[files]]
file = "config/discord-mc-chat/discord-mc-chat.json"
hash = "6e6e7dd8749a8448f85996a924f57dfbdfe68f2e485480846ea7f481dfe4ea4d"

[[files]]
file = "config/fabric-seasons.json"
hash = "57c9f9eac24cdb072c858155ef63d353b708b728186455f45b9e2f09eb49a942"

[[files]]
file = "config/iris.properties"
hash = "99ac8a2dfd17f7b4ed038c02255a279296ecad90e48a5b7196ac4f73260d57ee"

[[files]]
file = "config/worldedit/schematics/butler.schem"
hash = "b3304afb33cd9ebfced2c06b990dd3e20675a64a35589c156b0b06630129d9f4"

[[files]]
file = "config/worldedit/schematics/mcc.schem"
hash = "84a3c8848190eb4832f8e47798ba686a35d83e682f01f3d7ba8b228acce9f0e2"

[[files]]
file = "docs/minecraft-college-setup-guide.md"
hash = "5d717577101ef8c5eced132a2ddf43338f78e0b0906cc01aac9a2828a54a08de"

[[files]]
file = "docs/server-plan.md"
hash = "bf520f7154bfb854775ed476f781ad462cab86ca68b67c56f4a8936baf82b557"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap.config"
hash = "95495226d48919c172eee4119a280275cdf0d63837a282878bce6ae4c66b14d5"

[[files]]
file = "journeymap/config/6.0/journeymap.minimap2.config"
hash = "408e7f0df62763aa355abbca8293e5e4ee8fe3ac687657768fd51fd96f164d78"

[[files]]
file = "logo.png"
hash = "fb392fed200fb97a293972a79eb96fbce6104b3ebd2ec669a3b9c1a120447025"

[[files]]
file = "modpack-info.json"
hash = "edd0c0204f392a6afd8ce529ef4303c2b68b641b2f9e03b99a7534d8b0e205c7"

[[files]]
file = "mods/appleskin.pw.toml"
hash = "e9dbd0306dd34da5fe43f5880de09950d312ba7ab60880c69b555b197e2a1007"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "5b9618476350398ad0d25b5bf3a41521dd015baa22e4bfe8db685625a3a2c697"
metafile = true

[[files]]
file = "mods/athena-ctm.pw.toml"
hash = "dbc1220d5b4e4a1615ccecfb7d482349020919700ad9bafb5f690c2d4adbb5b2"
metafile = true

[[files]]
file = "mods/better-sleep.pw.toml"
hash = "642e862f4be77db00a3afd2105efb10b81d874e0afc32c621cf1bb7f087fe410"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "84d5506d7a81b89cb1abf6e2dd4d2cb0f5eed5b4587c19c73ffc2e954989019d"
metafile = true

[[files]]
file = "mods/chipped.pw.toml"
hash = "f6b6c905a485c11b69b8b6dcac0d0b78f0043c0869ec1ae99bb74bb2c88c93ee"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "8792552849464a56b066435132a3563a81e1ed70afedcc8c9dd1da602cda1d5f"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a112512699928e5504f2e826194c60881f949902fee6c6bef5f3539fcb90db75"
metafile = true

[[files]]
file = "mods/controlling.pw.toml"
hash = "a2316b374cef47920604f89b1ce784aa3e1e4c80088259e7704ce5fe47c14721"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "c798b7e3414891c8db42e93335d21a104d40a235e35a6a42b47e0a213c9a6be9"
metafile = true

[[files]]
file = "mods/distanthorizons.pw.toml"
hash = "b9cb49dc2d791b759ac553cf28ca33a6440d219f48ebc0ba4eb100df37c73889"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "27c4150b810e326b1097a7768c593c93e89484fcee0b8c4a8f3d48a6896cf649"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "2831d2be7f52107b8cb23145f8812485c7ee12107a4eabf47d39d5b5d778cf04"
metafile = true

[[files]]
file = "mods/fabric-seasons-extras.pw.toml"
hash = "7833078d6daef78131f8cc43425ef5292413e966154ac3ce305e17196bd530e2"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "d40faa8d75ec7b4741146b033dca1d47368868985da3dcc6dc32fd9def5841d9"
metafile = true

[[files]]
file = "mods/fabricord.pw.toml"
hash = "5749724ac7f1331ec4bd6469e93b650501e3d4e455c750c7b9068f99c9574c9d"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "310deca3cd563b915d447e707bd138c3ff3ae0fd40f648daabacc7350437cd32"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "0ac4faa43fa6348191b94dfc7c0ed8a1b09f6dc3b36837b029aa023853019503"
metafile = true

[[files]]
file = "mods/flan.pw.toml"
hash = "945c52db21b5c778f7292bbb4979fb844b2255168b15bf1eee2285c7ce5b6217"
metafile = true

[[files]]
file = "mods/handcrafted.pw.toml"
hash = "830613b40e4ceb047d011b00190f57c350d30fbc1d244c56722f4617ae2a57de"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "c86e0fe57fbe042c8444a9c63933e89b5fdd50f325bb8a9796d0e7cca8735c89"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "f40b2722e2f26e50909aaa4579beac0d107a96a524adb5ffedac3bf183cceee2"
metafile = true

[[files]]
file = "mods/journeymap.pw.toml"
hash = "67fe6ad4a8c1b5f64a8b2ecd0aac7bcd7103447494df8f08fd8a4124411229a5"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "8ecd67f8269c6317a0dc59edebcb9d6b3730f3adf26532e3a6c664804983c4ec"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0f8827c966b0d439692f3b8d578a47c203cd0aec0043ea4fd3fc00025a13ab79"
metafile = true

[[files]]
file = "mods/macaws-bridges.pw.toml"
hash = "80474d91d72222900c31b5829a18d735942a08a14ea6e8bf61609770003f06cc"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "77bf6a03e9d6f74b1ed5d03095caa843ad15eb9a6e2a59c1d051dfb606084070"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "66365a7cd0eab491a46ffe6eea730bdc18a847acbf7427389b11523513f4d8ed"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "7a7a3dfab20334737bf31b367e484038b1b283eb9911a2a3bc4727700d2ae4a4"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "8814c7931c35f9c2c253cb4c3b62c120d1e14f608d3011e91ba303afc0154a53"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "9eb1325dc680a7bdba0ff97a27e3b6894b2177911518c7cb86aad32eef48adb6"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "5b341b230a1c90db349b54b27a8056a4651961836acb915c5dc68e882ab358f6"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "0b1d715cd850c6ce4c1bd42fdb331f5f79ff2e0e7b5138812f2156cdb5f60694"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "941a5aac1b441e2b4bd0c8465ea7e9f5c6826b4f99aa8c4ba63b3b657b6e7530"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "f0440bc0276d813e5de5f87388c8853e13842358383084571093600abc7d5a2f"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "72888447d9d18619c6260001033c1a8c81d27687717e920dea86147792ff1f73"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "7775fd30aa27e84dbc3acb28ce34e4f703d1cd503786da5cb84f2813a57acf15"
metafile = true

[[files]]
file = "mods/resourceful-lib.pw.toml"
hash = "cb361ef34fb46e3fe719a08b08ba4ea8e0fda33927b8b23f1999c8e451bb02dc"
metafile = true

[[files]]
file = "mods/searchables.pw.toml"
hash = "bd1cc305fbff4a3b13f4406f22cf6c33bb4cb17dab0327e962e521c19a53c9ec"
metafile = true

[[files]]
file = "mods/simple-discord-rpc.pw.toml"
hash = "051f526e3f8a093006e2f0ed10a784647fa8e8ed738e9ccaa81f401ce5441e77"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "a57a0cf4e8bc2b3997d03a3d1748a756d429bcc2f89e6814555ea4be846c279d"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "9a987bcd2646a2ab741e7f609b43cb2d9c9daba765323b5a77d506b0ac7f4207"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "f93fc683b99d7405f4d54cdd799e7adbc99388a10c44e0271acb11276de4a934"
metafile = true

[[files]]
file = "mods/storagedrawers.pw.toml"
hash = "7ce16912c8ffa23e398c93c8060634ed3ded1fa4fe40384216b53193a1fd8a08"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "177cfd45dd255736ca80f81e7a38e907dcce205e6d4cd2f8aa98602d92a57a30"
metafile = true

[[files]]
file = "mods/worldedit.pw.toml"
hash = "f1670113ba6c7687790c33c13521505caf0fb59a50a253e9533e9f6ebe3cf8c9"
metafile = true

[[files]]
file = "mrpack4server-0.5.0.jar"
hash = "e89bdaafc3f0f5c07ed912cb29c6beab61716579960780eb7c5b7129bbaac65f"

[[files]]
file = "options.txt"
hash = "5f30cc88a38375250345b391ce650516f78b73d8b2c041da4fca72c09e0f679d"

[[files]]
file = "server-config.py"
hash = "6b3ac00f389367488ab1777935b71556d0c08d82874e8d723af5613f89f06c0d"

[[files]]
file = "server.properties"
hash = "00afe7fece2b78adee18cf2ea96e1ffdd3fb5ccfe1838be6dd671f7b03c5d0b4"

[[files]]
file = "shaderpacks/BSL_v10.0.zip"
hash = "b6e79a4f5746bd0b2bd8d54bb4c430539e7e747e8679ac985bc07368422e4e09"

[[files]]
file = "shaderpacks/ComplementaryReimagined_r5.6.1.zip"
hash = "33153747d25fbee470acb42ccf4f26b03cc551bb900d4c6d3389b5500dd84839"
