name = "MCC"
author = "Slash"
version = "0.9.40"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63e2ecfcddeaf88382ef97695584f5f6b93cf42d0333f66b1306268725750254"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
