name = "TBA"
author = "Slash"
version = "0.9.79"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f43254427e7b8b26c0bea7ee90023a1f2f4b8e121969ca97e2a0bc44f329e088"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
