name = "TBA"
author = "Slash"
version = "0.9.72"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0a5895ea9c07e1faa5dabba2628f3297dd565d54d32d3e2986a3031cd0db27b7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
