name = "TBA"
author = "Slash"
version = "0.9.77"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd1dddc72b83a2ae434f8e50163bebafb83612815869626e21fe57ea904bb7d7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
