name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2a97090d5fb3589ff9eaa84100b6d3bacf67d252d7cf6546489c3df411395cdd"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
