name = "MCC"
author = "Slash"
version = "0.9.56"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2e5f5b3cd0b5e76640253f37a0535f07df05e4cd7331a55f9be8019cdbd9ac95"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
