name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.11"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "393c0713fc5a80861bf43a4a92f97a5ba05e184bef79d97c723ce0e739ec7539"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
