name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.4"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ec752f98911b8ad72eb2fe8472a6e231d20af21123cb5bd0d15a9c9a68781ebd"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
