name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.12"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cea4c37adac1d58bbd0bd05b32d077645427ef39f0da137ed18519a5d0c0143"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
