name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.16"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2feaae6e0b6d5076096cc5e1947477e22743b811ad07261b6acbfc282737e00c"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
