name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "edaa636d77356a542cf9dfdb6336f7b5f39396cdcfe6cbf997985331013d7ad7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
