name = "MCC"
author = "Slash"
version = "0.9.55"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "968c5a3b673e75d3fe308dc56075aa5a0aba03844fbfc1f23861130dbe010f03"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
