name = "TBA"
author = "Slash"
version = "0.9.68"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a245a0087792565bc4ce2ed51197d94f2525922b00d2bf07c3e1269bed004e10"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
