name = "TBA"
author = "Slash"
version = "0.9.90"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "95d4b08e086e8dd7944b9e5e4c603d775024bee1b6e619146771f3bc089aa6e0"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
