name = "MCC"
author = "Slash"
version = "0.9.27"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9b5415a2da53652ff2f56577fc10ae61969fd2bddaf99bef54d98b5b34929166"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
