name = "MCC"
author = "Slash"
version = "0.9.46"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f1dfd4b6dbbba6672e55d635e449efb8bf3b0c8379552ecd80a1118e5f98072"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
