name = "MCC"
author = "Slash"
version = "0.9.41"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e9a53994d047bc811bffb1fee1f1d0c28013486c3c5e815a3aae879323af76d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
