name = "TBA"
author = "Slash"
version = "0.9.94"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f2a03e40e80ffb076709a0f67d38c96f62917c7df5c7559f90d06b3125993b7a"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
