name = "TBA"
author = "Slash"
version = "0.9.94"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8676deecc985b3ef33887c63f26d00382651d7444b15e4ff69ae4c7e757e3225"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
