name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.23"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cedd6825dc1d8d9949defbaa53e1731831b834726050af3cde1f5d98ef85304"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
