name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5cfd62168416bf0e48f743be28b33e6cd0ef7304ce6d908b483b0ce05bf79e94"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
