name = "MCC"
author = "Slash"
version = "0.9.37"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7a3bda2009617729574d2177aff883848eeb8b1bcf9a3f10d7d62968c6b41770"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
