name = "TBA"
author = "Slash"
version = "0.9.83"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c2554954bc604188303a034210c27a07a0787a98395ae0e6e8fabe0b589bc979"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
