name = "TBA"
author = "Slash"
version = "0.9.70"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0649eb0bcefee706f99008ee7c342357f92980e7582e4bb4e48714f39e20bd64"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
