name = "MCC"
author = "Slash"
version = "0.9.60"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "db0ce4b0141b536d42bb6c1bbae9c18e7f1631e9ac2f1a8ceadb55e073bbaa95"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
