name = "TBA"
author = "Slash"
version = "0.9.84"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "22fc51519037b2a7c9b69261205b82d32876f95e6970e5b2bd408767f091e20f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
