name = "TBA"
author = "Slash"
version = "0.9.88"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8ed259419426366cf968f46dd5f762d4ff96d9548a45df6ce8c3802358c65b4"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
