name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.26"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6e75cd729ad2f47ac0a41d382d51f709f9e8cf46c45daf861a0df6822ae0b2d"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
