name = "Minecraft College"
author = "Slash"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f8e2092f513ee6034ffa426d756af76b4cdef4249d6c335bf9c8bb79f0a67b2"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
