name = "MCC"
author = "Slash"
version = "0.9.49"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6926c95ff84a5d2c8c67b43acd97ed7b1ba0b930e12c5c376731ef76eafa431f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
