name = "TBA"
author = "Slash"
version = "0.9.73"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d68f355d222f6d794bf4f25cc19a7a63f6df6be6f24193d9a5c27eb1de22a151"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
