name = "MCC"
author = "Slash"
version = "0.9.59"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "abe58505e848f072ef449e31d3aea853864fe57aa09ccde975ddf08f3bb8206a"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
