name = "MCC"
author = "Slash"
version = "0.9.34"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d5f2fb7ab24462f04452eb945e6e0f39986b32f920aba965f0932dfcb00ed879"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
