name = "TBA"
author = "Slash"
version = "0.9.92"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "65e611ed4b4542255c2f8eecef17bad6b48906ead7a573622ce45bdbb4dbf2c7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
