name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a91b554489e2c0754247d2a8e562499a3c04f22c488c96de44e780334377bd24"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
