name = "MCArtsAndCrafts"
author = "Slash"
version = "0.9.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a9b3122ee6dc19d2ef63f9de7835aeacf445b67915db44d49e96cbb61909a8f"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
