name = "MCC"
author = "Slash"
version = "0.9.38"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c075f69a0fa036ca1d4a2a0151bbf74fc628dd155e706fe11e7d8f30a5e18ad7"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
