name = "TBA"
author = "Slash"
version = "0.9.89"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51fb74c5b7508ae80cfc4f0dc172b0a14d60f5c3a32b2e88b612f3b480108157"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
