name = "TBA"
author = "Slash"
version = "0.9.63"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d288dcc7805c316debb59176a46f4bca47a5bb1786113b3995e3c3242bd954df"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
